name: Check Docs Links

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check README
        uses: becheran/mlc@v0.15.4
        with:
          args: ./README.md

      - name: Check Docs
        uses: becheran/mlc@v0.15.4
        with:
          args: ./docs
